# Generated by Django 5.2.10 on 2026-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_bureaumessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Tunivisions Kairouan', max_length=120, verbose_name='Nom affiché')),
                ('description', models.CharField(default='Plateforme officielle de coordination du club et de ses pôles.', max_length=255, verbose_name='Présentation')),
                ('quick_links_title', models.CharField(default='Liens rapides', max_length=80)),
                ('events_link_label', models.CharField(default='Événements', max_length=80)),
                ('announcements_link_label', models.CharField(default='Annonces', max_length=80)),
                ('contact_title', models.CharField(default='Contact', max_length=80)),
                ('contact_email', models.EmailField(default='med2006dali@gmail.com', max_length=254)),
                ('copyright_text', models.CharField(default='© 2026 Tunivisions Kairouan. Tous droits réservés.', max_length=160)),
            ],
            options={
                'verbose_name': 'Configuration du pied de page',
                'verbose_name_plural': 'Configuration du pied de page',
            },
        ),
    ]
