# Generated by Django 5.2.10 on 2026-10-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_secondary_role_alter_rolepermission_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('president', 'Président'), ('vp_rh', 'VP RH'), ('assistant_rh', 'Assistant RH'), ('vp_mkc', 'VP MKC'), ('assistant_comm_mkg', 'Assistant Comm/MKG'), ('vp_events', 'VP Events'), ('assistant_event', 'Assistant Événementiel'), ('vp_bd', 'VP BD'), ('assistant_bd', 'Assistant BD'), ('active_member', 'Membre Actif'), ('owner', 'Ancien Owner'), ('vice_president', 'Ancien Vice-Président'), ('partnerships', 'Ancien Responsable Partenariats'), ('design', 'Ancien Responsable Design'), ('treasurer', 'Ancien Trésorier'), ('secretary', 'Ancien Secrétaire'), ('hr', 'Ancien Responsable RH'), ('media', 'Ancien Responsable Media'), ('events_manager', 'Ancien Responsable Événement'), ('member', 'Ancien Membre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('president', 'Président'), ('vp_rh', 'VP RH'), ('assistant_rh', 'Assistant RH'), ('vp_mkc', 'VP MKC'), ('assistant_comm_mkg', 'Assistant Comm/MKG'), ('vp_events', 'VP Events'), ('assistant_event', 'Assistant Événementiel'), ('vp_bd', 'VP BD'), ('assistant_bd', 'Assistant BD'), ('active_member', 'Membre Actif'), ('owner', 'Ancien Owner'), ('vice_president', 'Ancien Vice-Président'), ('partnerships', 'Ancien Responsable Partenariats'), ('design', 'Ancien Responsable Design'), ('treasurer', 'Ancien Trésorier'), ('secretary', 'Ancien Secrétaire'), ('hr', 'Ancien Responsable RH'), ('media', 'Ancien Responsable Media'), ('events_manager', 'Ancien Responsable Événement'), ('member', 'Ancien Membre')], default='member', max_length=30, verbose_name='Primary Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_role',
            field=models.CharField(blank=True, choices=[('president', 'Président'), ('vp_rh', 'VP RH'), ('assistant_rh', 'Assistant RH'), ('vp_mkc', 'VP MKC'), ('assistant_comm_mkg', 'Assistant Comm/MKG'), ('vp_events', 'VP Events'), ('assistant_event', 'Assistant Événementiel'), ('vp_bd', 'VP BD'), ('assistant_bd', 'Assistant BD'), ('active_member', 'Membre Actif'), ('owner', 'Ancien Owner'), ('vice_president', 'Ancien Vice-Président'), ('partnerships', 'Ancien Responsable Partenariats'), ('design', 'Ancien Responsable Design'), ('treasurer', 'Ancien Trésorier'), ('secretary', 'Ancien Secrétaire'), ('hr', 'Ancien Responsable RH'), ('media', 'Ancien Responsable Media'), ('events_manager', 'Ancien Responsable Événement'), ('member', 'Ancien Membre')], max_length=20, null=True, verbose_name='Secondary Role (Optional)'),
        ),
    ]
